settings:
  title: 'Status Page'
  url: 'https://status.demosjarco.dev' # used for Slack messages
  logo: square_logo.svg # image in ./public/ folder
  daysInHistogram: 72 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: main-site
    name: demosjarco.dev
    description: 'AWS US West (Oregon)'
    url: 'https://demosjarco.dev/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: main-cdn
    name: cdn.demosjarco.dev
    description: 'Backblaze B2'
    url: 'https://cdn.demosjarco.dev/file/demosjarco-portfolio/images/logo.svg'
    method: GET
    expectStatus: 200
    linkable: false
  
  # - id: fdb-extension
  #   name: FDB Extension
  #   description: 'AWS US West (Oregon)'
  #   url: 'https://missions.fortnitedb.com/video-component.html'
  #   method: GET
  #   expectStatus: 200
  #   linkable: false
  
  # - id: fdb-extension-backend
  #   name: FDB Extension Backend
  #   description: 'AWS US West (Oregon)'
  #   url: 'https://missions.fortnitedb.com/socket.io/?EIO=4&transport=websocket'
  #   method: GET
  #   expectStatus: 400
  #   linkable: false
  
  # - id: fdb-extension-cdn
  #   name: FDB Extension CDN
  #   description: 'Backblaze B2'
  #   url: 'https://b2.fortnitedb.com/file/PeepoT/a.png'
  #   method: GET
  #   expectStatus: 200
  #   linkable: false
  
  - id: mc-peyton-batmanning
    name: Minecraft - Peyton Batmanning
    url: 'https://api.mcsrvstat.us/simple/games.demosjarco.dev'
    method: GET
    expectStatus: 200
    linkable: false
  
  - id: mc-dedidated-minecwaft-sewvew
    name: Minecraft - Dedidated Minecwaft Sewvew
    url: 'https://api.mcsrvstat.us/simple/games.demosjarco.dev:31339'
    method: GET
    expectStatus: 200
    linkable: false
  
  - id: mc-legit
    name: Minecraft - Legit
    url: 'https://api.mcsrvstat.us/simple/games.demosjarco.dev:34323'
    method: GET
    expectStatus: 200
    linkable: false